### ISSUE TITLE
Nanopore methylation

### ISSUE THREAD

**Issue by yyoshiaki** [ykohki/mishima2019#1]
すでにDNA methylationをNanoporeで読む技術はかなり確立しています。
https://academic.oup.com/nar/article/47/8/e46/5356940

Direct RNA sequencingによるfull length sequenceやm6AなどのRNA modificationも難しいけど可能なようです。
https://www.nature.com/articles/s41467-019-11713-9

**Comment by ykohki** [comment]
追記させて頂きました。
